[tools]
aws-cli = "latest"
docker-cli = "latest"
doggo = "latest"
eza = "latest"
go = "latest"
lua = "latest"
neovim = "latest"
node = "latest"
packer = "latest"
opentofu = "latest"
ripgrep = "latest"
tlrc = "latest"
vivid = "latest"
yq = "latest"
jq = "latest"
yarn = "latest"
python = "3.13"
